from .base import (
    Location,
    Contact,
    University,
    Faculty,
    Department,
    EduStats,
    EduScore,
    # String constants
    UNIVERSITY_TYPE_PUBLIC,
    UNIVERSITY_TYPE_PRIVATE,
    UNIVERSITY_TYPE_COMMUNITY,
    UNIVERSITY_TYPE_FOR_PROFIT,
    UNIVERSITY_TYPE_NON_PROFIT
)
# from .uniAcademic import (
#     Course
# )
from .uniProgram import (
    Program,
    # String constants
    PROGRAM_LEVEL_BACHELOR,
    PROGRAM_LEVEL_MASTER,
    PROGRAM_LEVEL_PHD,
    PROGRAM_LEVEL_ASSOCIATE,
    PROGRAM_LEVEL_CERTIFICATE,
    PROGRAM_LEVEL_DIPLOMA
)
from .uniPeople import (
    Person,
    Staff,
    # String constants
    GENDER_MALE,
    GENDER_FEMALE,
    GENDER_OTHER,
    GENDER_PREFER_NOT_TO_SAY
)
from .uniResearch import (
    ResearchLab
)
from .uniScholarship import (
    # Scholarship models
    ScholarshipProvider,
    Scholarship,
    ScholarshipEligibility,
    ScholarshipMetrics,
    # String constants
    PROVIDER_TYPE_GOVERNMENT,
    PROVIDER_TYPE_UNIVERSITY,
    PROVIDER_TYPE_NGO,
    PROVIDER_TYPE_PRIVATE_COMPANY,
    PROVIDER_TYPE_FOUNDATION,
    PROVIDER_TYPE_INTERNATIONAL_ORGANIZATION,
    PROVIDER_TYPE_INDIVIDUAL_DONOR,
    CRITERIA_TYPE_GPA,
    CRITERIA_TYPE_NATIONALITY,
    CRITERIA_TYPE_INCOME_LEVEL,
    CRITERIA_TYPE_PROGRAM,
    CRITERIA_TYPE_DEGREE_LEVEL,
    CRITERIA_TYPE_AGE,
    CRITERIA_TYPE_GENDER,
    CRITERIA_TYPE_FIELD_OF_STUDY,
    CRITERIA_TYPE_ACADEMIC_ACHIEVEMENT,
    CRITERIA_TYPE_FINANCIAL_NEED,
    CRITERIA_TYPE_COMMUNITY_SERVICE,
    CRITERIA_TYPE_LEADERSHIP,
    CRITERIA_TYPE_SPORTS,
    CRITERIA_TYPE_ARTS,
    CRITERIA_TYPE_RESEARCH_INTEREST,
    SCHOLARSHIP_TYPE_MERIT_BASED,
    SCHOLARSHIP_TYPE_NEED_BASED,
    SCHOLARSHIP_TYPE_ATHLETIC,
    SCHOLARSHIP_TYPE_ACADEMIC,
    SCHOLARSHIP_TYPE_RESEARCH,
    SCHOLARSHIP_TYPE_DIVERSITY,
    SCHOLARSHIP_TYPE_INTERNATIONAL,
    SCHOLARSHIP_TYPE_MINORITY,
    SCHOLARSHIP_TYPE_FIRST_GENERATION,
    SCHOLARSHIP_TYPE_FIELD_SPECIFIC
)
from .uniCampus import (
    Campus,
    Facility,
    # String constants
    FACILITY_TYPE_LIBRARY,
    FACILITY_TYPE_LABORATORY,
    FACILITY_TYPE_DORMITORY,
    FACILITY_TYPE_SPORTS_COMPLEX,
    FACILITY_TYPE_AUDITORIUM,
    FACILITY_TYPE_CLASSROOM,
    FACILITY_TYPE_CAFETERIA,
    FACILITY_TYPE_ADMINISTRATIVE
)

__all__ = [
    # University schemas - base
    "Location",
    "Contact",
    "University",
    "EduStats",
    "EduScore",
    
    # University schemas - campus
    "Campus",
    
    # University schemas - academic
    "Faculty",
    "Department",
    "Program",
    
    # University schemas - people
    "Person",
    "Staff",
    
    # University schemas - research
    "ResearchLab",
    
    # Scholarship models
    "ScholarshipProvider",
    "Scholarship",
    "ScholarshipEligibility",
    "ScholarshipMetrics",
    
    # University schemas - uniCampus
    "Facility",
    
    # String constants - info
    "UNIVERSITY_TYPE_PUBLIC",
    "UNIVERSITY_TYPE_PRIVATE",
    "UNIVERSITY_TYPE_COMMUNITY",
    "UNIVERSITY_TYPE_FOR_PROFIT",
    "UNIVERSITY_TYPE_NON_PROFIT",
    
    # String constants - program levels
    "PROGRAM_LEVEL_BACHELOR",
    "PROGRAM_LEVEL_MASTER",
    "PROGRAM_LEVEL_PHD",
    "PROGRAM_LEVEL_ASSOCIATE",
    "PROGRAM_LEVEL_CERTIFICATE",
    "PROGRAM_LEVEL_DIPLOMA",
    
    # String constants - gender
    "GENDER_MALE",
    "GENDER_FEMALE",
    "GENDER_OTHER",
    "GENDER_PREFER_NOT_TO_SAY",
    
    # Scholarship string constants
    "PROVIDER_TYPE_GOVERNMENT",
    "PROVIDER_TYPE_UNIVERSITY",
    "PROVIDER_TYPE_NGO",
    "PROVIDER_TYPE_PRIVATE_COMPANY",
    "PROVIDER_TYPE_FOUNDATION",
    "PROVIDER_TYPE_INTERNATIONAL_ORGANIZATION",
    "PROVIDER_TYPE_INDIVIDUAL_DONOR",
    "CRITERIA_TYPE_GPA",
    "CRITERIA_TYPE_NATIONALITY",
    "CRITERIA_TYPE_INCOME_LEVEL",
    "CRITERIA_TYPE_PROGRAM",
    "CRITERIA_TYPE_DEGREE_LEVEL",
    "CRITERIA_TYPE_AGE",
    "CRITERIA_TYPE_GENDER",
    "CRITERIA_TYPE_FIELD_OF_STUDY",
    "CRITERIA_TYPE_ACADEMIC_ACHIEVEMENT",
    "CRITERIA_TYPE_FINANCIAL_NEED",
    "CRITERIA_TYPE_COMMUNITY_SERVICE",
    "CRITERIA_TYPE_LEADERSHIP",
    "CRITERIA_TYPE_SPORTS",
    "CRITERIA_TYPE_ARTS",
    "CRITERIA_TYPE_RESEARCH_INTEREST",
    "SCHOLARSHIP_TYPE_MERIT_BASED",
    "SCHOLARSHIP_TYPE_NEED_BASED",
    "SCHOLARSHIP_TYPE_ATHLETIC",
    "SCHOLARSHIP_TYPE_ACADEMIC",
    "SCHOLARSHIP_TYPE_RESEARCH",
    "SCHOLARSHIP_TYPE_DIVERSITY",
    "SCHOLARSHIP_TYPE_INTERNATIONAL",
    "SCHOLARSHIP_TYPE_MINORITY",
    "SCHOLARSHIP_TYPE_FIRST_GENERATION",
    "SCHOLARSHIP_TYPE_FIELD_SPECIFIC",
    
    # String constants - uniCampus
    "FACILITY_TYPE_LIBRARY",
    "FACILITY_TYPE_LABORATORY",
    "FACILITY_TYPE_DORMITORY",
    "FACILITY_TYPE_SPORTS_COMPLEX",
    "FACILITY_TYPE_AUDITORIUM",
    "FACILITY_TYPE_CLASSROOM",
    "FACILITY_TYPE_CAFETERIA",
    "FACILITY_TYPE_ADMINISTRATIVE"
]
